site_name: PolyFEM
site_url: "http://polyfem.github.io/polyfem/"
repo_name: "polyfem/polyfem"
repo_url: "https://github.com/polyfem/polyfem"
edit_uri: "../polyfem.github.io/edit/docs/docs/"
site_description: "A polyvalent C++ FEM library"
copyright: Copyright &copy; 2018–2021 PolyFEM Group; <a href="https://github.com/polyfem/polyfem/blob/master/LICENSE">MIT License</a>
# strict: true
docs_dir: "docs"
remote_branch: "master"
theme:
  name: material
  custom_dir: 'docs/theme'
  favicon: "img/xxx.ico"
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "light green"
      accent: "green"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "green"
      accent: "green"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/polyfem"
extra_css:
  - theme/extra.css
markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - toc:
      permalink: true
  - markdown.extensions.smarty
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      user: polyfem
      repo: polyfem
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  # - mknotebooks:
  #   execute: true
  #   preamble: "docs/plot_to_md.py"
  #   timeout: -1
  - git-revision-date
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
  - include-markdown
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - General:
    - Home: index.md
    - License: license.md
  - C++:
    - Home: cxx_index.md
    - JSON Input: json.md
    - JSON Specification: json_defaults_and_spec.md
    - Docs: https://polyfem.github.io/polyfem/
  - Python:
    - Home: python.md
    - Jupyter Tutorial: python_examples.ipynb
    - Docs: polyfempy_doc.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    - IPC Quick Start Guide: tutorials/ipc_quick_start_guide/ipc_quick_start_guide.md
    - Multi-Material: tutorials/multi-material/multi-material.md
    - Screwing a Bolt into a Nut: tutorials/screw/screw.md
    - Robotics:
      - Pushing A Box: tutorials/sphere-pushing-box/sphere-pushing-box.md
      - Sling-shot: tutorials/sling-shot/sling-shot.md
    - Vision Proprioception: tutorials/vision-proprioception/vision-proprioception.md
  - Technical Details:
    - Formulations: details/formulations.md
    - Problems: details/problems.md
    - Time Integrators: details/time_integrators.md
    - Solvers: details/solvers.md
    - Contact: details/contact.md
    - Miscellaneous: details/miscellaneous.md
  - PolySolve: polysolve.md
