name: Build Website

on:
  workflow_dispatch:
  push:
    branches:
      - docs

permissions:
  contents: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate JSON Spec Documentation
        run: |
          git clone --depth=1 https://github.com/polyfem/polyfem.git
          git clone --depth=1 https://github.com/geometryprocessing/json-spec-engine.git
          pip install -r ./json-spec-engine/requirements.txt
          python ./json-spec-engine/docs/spec2html.py -i ./polyfem/input-spec.json -o ./docs/_json_spec.md
          python ./json-spec-engine/scripts/generate_defaults.py -i ./polyfem/input-spec.json -o ./docs/_json_defaults.json
          cp ./polyfem/LICENSE ./docs/_polyfem_license.txt

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
